version: '3'

services:
  auth_db:
    container_name: auth_db
    image: postgres:16.3-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      PGUSER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
      PGDATABASE: ${AUTH_DB_NAME}
      PGPORT: ${AUTH_DB_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "${AUTH_DB_PORT}:${AUTH_DB_PORT}"
    command: -p ${AUTH_DB_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 30s
      retries: 5
    networks:
      - pinting_net

  auth:
    container_name: auth
    image: pinting/auth:1.0.0
    restart: always
    build: .
    env_file:
      - ./env/.env
    ports:
      - '8080:8080'
    depends_on:
      auth_db:
        condition: service_healthy
    networks:
      - pinting_net

networks:
  pinting_net:
    driver: bridge

# volumes:
  # auth_db_vol:
  #   driver: local
  #   driver_opts:
  #     o: bind
  #     type: none
  #     device: ${AUTH_DB_VOL_PATH}